title: KCNA Study Tips
description: A place to keep my notes in documentation format.
theme: just-the-docs
color_scheme: dark

url: https://github.com/FrankAllotta/kubernetes-study-tips

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/FrankAllotta/kubernetes-study-tips